<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
final class InstructorLearnerTestSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::getDriverName() === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');
        }
        DB::table('video_progress')->whereIn('user_id', [9904, 9905, 9906])->delete();
        DB::table('lesson_progress')->whereIn('user_id', [9904, 9905, 9906])->delete();
        DB::table('enrollments')->whereIn('id', [9901, 9902, 9903, 9904])->delete();
        DB::table('orders')->whereIn('id', [9901, 9902, 9903, 9904])->delete();
        DB::table('lessons')->whereIn('id', [9901, 9902, 9903, 9904, 9905])->delete();
        DB::table('course_sections')->whereIn('id', [9901, 9902, 9903, 9904])->delete();
        DB::table('courses')->whereIn('id', [9901, 9902, 9903, 9904])->delete();
        DB::table('users')->whereIn('id', [9901, 9902, 9903, 9904, 9905, 9906, 9907])->delete();
        if (DB::getDriverName() === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }
        DB::table('users')->insert([
            [
                'id' => 9901,
                'full_name' => 'GV Test 1',
                'email' => 'ins.learner.test1@mindhub.test',
                'password_hash' => null,
                'role' => 'instructor',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'full_name' => 'GV Test 2',
                'email' => 'ins.learner.test2@mindhub.test',
                'password_hash' => null,
                'role' => 'instructor',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'full_name' => 'Admin Test',
                'email' => 'admin.learner.test@mindhub.test',
                'password_hash' => null,
                'role' => 'admin',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'full_name' => 'Learner Active Test',
                'email' => 'learner.active.test@mindhub.test',
                'password_hash' => null,
                'role' => 'learner',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9905,
                'full_name' => 'Learner Completed Test',
                'email' => 'learner.completed.test@mindhub.test',
                'password_hash' => null,
                'role' => 'learner',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9906,
                'full_name' => 'Learner Other Instructor Test',
                'email' => 'learner.other.ins.test@mindhub.test',
                'password_hash' => null,
                'role' => 'learner',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9907,
                'full_name' => 'GV Empty Test',
                'email' => 'ins.empty.test@mindhub.test',
                'password_hash' => null,
                'role' => 'instructor',
                'status' => 'active',
                'locked' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('courses')->insert([
            [
                'id' => 9901,
                'instructor_id' => 9901,
                'title' => 'Course Test Instructor 1',
                'slug' => 'course-test-instructor-1',
                'price' => 100000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'status' => 'published',
                'is_featured' => 0,
                'total_duration_seconds' => 3600,
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'instructor_id' => 9901,
                'title' => 'Course Test Instructor 1 Completed',
                'slug' => 'course-test-instructor-1-completed',
                'price' => 200000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'status' => 'published',
                'is_featured' => 0,
                'total_duration_seconds' => 3600,
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'instructor_id' => 9902,
                'title' => 'Course Test Instructor 2',
                'slug' => 'course-test-instructor-2',
                'price' => 300000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'status' => 'published',
                'is_featured' => 0,
                'total_duration_seconds' => 3600,
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'instructor_id' => 9907,
                'title' => 'Course Empty Instructor',
                'slug' => 'course-empty-instructor',
                'price' => 100000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'status' => 'published',
                'is_featured' => 0,
                'total_duration_seconds' => 1200,
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('course_sections')->insert([
            [
                'id' => 9901,
                'course_id' => 9901,
                'title' => 'Chương test 1',
                'sort_order' => 1,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'course_id' => 9901,
                'title' => 'Chương test 2',
                'sort_order' => 2,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'course_id' => 9903,
                'title' => 'Chương instructor khác',
                'sort_order' => 1,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'course_id' => 9902,
                'title' => 'Chương fallback last accessed',
                'sort_order' => 1,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('lessons')->insert([
            [
                'id' => 9901,
                'course_section_id' => 9901,
                'course_id' => 9901,
                'title' => 'Lesson completed test',
                'slug' => 'lesson-completed-test',
                'lesson_type' => 'video',
                'video_duration_seconds' => 900,
                'is_preview' => 0,
                'status' => 'published',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'course_section_id' => 9901,
                'course_id' => 9901,
                'title' => 'Lesson in progress test',
                'slug' => 'lesson-in-progress-test',
                'lesson_type' => 'text',
                'video_duration_seconds' => null,
                'is_preview' => 0,
                'status' => 'published',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'course_section_id' => 9902,
                'course_id' => 9901,
                'title' => 'Lesson not started test',
                'slug' => 'lesson-not-started-test',
                'lesson_type' => 'video',
                'video_duration_seconds' => 1200,
                'is_preview' => 0,
                'status' => 'published',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'course_section_id' => 9903,
                'course_id' => 9903,
                'title' => 'Lesson other instructor test',
                'slug' => 'lesson-other-instructor-test',
                'lesson_type' => 'video',
                'video_duration_seconds' => 1200,
                'is_preview' => 0,
                'status' => 'published',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9905,
                'course_section_id' => 9904,
                'course_id' => 9902,
                'title' => 'Lesson fallback last accessed test',
                'slug' => 'lesson-fallback-last-accessed-test',
                'lesson_type' => 'video',
                'video_duration_seconds' => 600,
                'is_preview' => 0,
                'status' => 'published',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('orders')->insert([
            [
                'id' => 9901,
                'course_id' => 9901,
                'user_id' => 9904,
                'order_code' => 'TEST-INS-LEARNER-9901',
                'status' => 'paid',
                'price_snapshot' => 100000,
                'amount' => 100000,
                'payment_status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'course_id' => 9902,
                'user_id' => 9905,
                'order_code' => 'TEST-INS-LEARNER-9902',
                'status' => 'paid',
                'price_snapshot' => 200000,
                'amount' => 200000,
                'payment_status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'course_id' => 9903,
                'user_id' => 9906,
                'order_code' => 'TEST-INS-LEARNER-9903',
                'status' => 'paid',
                'price_snapshot' => 300000,
                'amount' => 300000,
                'payment_status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'course_id' => 9902,
                'user_id' => 9904,
                'order_code' => 'TEST-INS-LEARNER-9904',
                'status' => 'paid',
                'price_snapshot' => 200000,
                'amount' => 200000,
                'payment_status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('enrollments')->insert([
            [
                'id' => 9901,
                'user_id' => 9904,
                'course_id' => 9901,
                'order_id' => 9901,
                'status' => 'active',
                'progress_percent' => 45.5,
                'enrolled_at' => now()->subDays(10),
                'completed_at' => null,
                'last_accessed_at' => now()->subDay(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9902,
                'user_id' => 9905,
                'course_id' => 9902,
                'order_id' => 9902,
                'status' => 'completed',
                'progress_percent' => 100,
                'enrolled_at' => now()->subDays(20),
                'completed_at' => now()->subDays(2),
                'last_accessed_at' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9903,
                'user_id' => 9906,
                'course_id' => 9903,
                'order_id' => 9903,
                'status' => 'active',
                'progress_percent' => 20,
                'enrolled_at' => now()->subDays(5),
                'completed_at' => null,
                'last_accessed_at' => now()->subDay(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9904,
                'user_id' => 9904,
                'course_id' => 9902,
                'order_id' => 9904,
                'status' => 'active',
                'progress_percent' => 10,
                'enrolled_at' => now()->subDay(),
                'completed_at' => null,
                'last_accessed_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('lesson_progress')->insert([
            [
                'lesson_id' => 9901,
                'user_id' => 9904,
                'status' => 'completed',
                'started_at' => now()->subDays(3),
                'completed_at' => now()->subDays(3)->addMinutes(20),
                'learning_duration_seconds' => 1200,
                'last_accessed_at' => now()->subDays(3)->addMinutes(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_id' => 9902,
                'user_id' => 9904,
                'status' => 'in_progress',
                'started_at' => now()->subDay(),
                'completed_at' => null,
                'learning_duration_seconds' => 300,
                'last_accessed_at' => now()->subDay(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_id' => 9905,
                'user_id' => 9904,
                'status' => 'in_progress',
                'started_at' => now()->subHours(6),
                'completed_at' => null,
                'learning_duration_seconds' => 180,
                'last_accessed_at' => now()->subHours(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('video_progress')->insert([
            [
                'lesson_id' => 9901,
                'user_id' => 9904,
                'current_second' => 900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_id' => 9905,
                'user_id' => 9904,
                'current_second' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}