<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogCoursesSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $instructor01Id = (int) DB::table('users')->where('email', 'cat.instructor01@example.com')->value('id');
        $instructor02Id = (int) DB::table('users')->where('email', 'cat.instructor02@example.com')->value('id');

        $courses = [
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_PUBLISHED Laravel API Featured',
                'slug' => 'cat-course-published-laravel-api-featured',
                'short_description' => 'Khóa Laravel API public, featured.',
                'description' => 'Học xây dựng REST API với Laravel, MySQL, Resource, Service, Repository.',
                'thumbnail_url' => 'https://example.com/images/cat-laravel-api.jpg',
                'intro_video_url' => 'https://example.com/videos/cat-laravel-api.mp4',
                'price' => 1200000,
                'sale_price' => 799000,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => 'Biết PHP cơ bản',
                'outcomes' => 'Xây dựng được REST API Laravel',
                'status' => 'published',
                'is_featured' => true,
                'total_duration_seconds' => 36000,
                'published_at' => $now->copy()->subDays(10),
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_PUBLISHED PHP MySQL Best Selling',
                'slug' => 'cat-course-published-php-mysql-best-selling',
                'short_description' => 'Khóa PHP MySQL nhiều enrollment nhất.',
                'description' => 'Học PHP, MySQL, database design.',
                'thumbnail_url' => 'https://example.com/images/cat-php-mysql.jpg',
                'intro_video_url' => 'https://example.com/videos/cat-php-mysql.mp4',
                'price' => 900000,
                'sale_price' => 499000,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => 'Không yêu cầu kinh nghiệm',
                'outcomes' => 'Nắm được PHP và MySQL căn bản',
                'status' => 'published',
                'is_featured' => false,
                'total_duration_seconds' => 28000,
                'published_at' => $now->copy()->subDays(20),
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor02Id,
                'title' => 'COURSE_PUBLISHED React Latest',
                'slug' => 'cat-course-published-react-latest',
                'short_description' => 'Khóa React mới nhất.',
                'description' => 'Học React, component, state, props.',
                'thumbnail_url' => 'https://example.com/images/cat-react-latest.jpg',
                'intro_video_url' => 'https://example.com/videos/cat-react-latest.mp4',
                'price' => 1500000,
                'sale_price' => 1199000,
                'level' => 'intermediate',
                'language' => 'vi',
                'requirements' => 'Biết HTML, CSS, JavaScript',
                'outcomes' => 'Xây dựng được UI React',
                'status' => 'published',
                'is_featured' => true,
                'total_duration_seconds' => 42000,
                'published_at' => $now->copy()->subDay(),
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor02Id,
                'title' => 'COURSE_PUBLISHED Free UI Design',
                'slug' => 'cat-course-published-free-ui-design',
                'short_description' => 'Khóa miễn phí để test sort price_asc.',
                'description' => 'Học UI design căn bản.',
                'thumbnail_url' => 'https://example.com/images/cat-free-ui-design.jpg',
                'intro_video_url' => 'https://example.com/videos/cat-free-ui-design.mp4',
                'price' => 0,
                'sale_price' => null,
                'level' => 'all_levels',
                'language' => 'vi',
                'requirements' => 'Không yêu cầu',
                'outcomes' => 'Biết thiết kế giao diện cơ bản',
                'status' => 'published',
                'is_featured' => false,
                'total_duration_seconds' => 12000,
                'published_at' => $now->copy()->subDays(3),
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_DRAFT Not Public',
                'slug' => 'cat-course-draft-not-public',
                'short_description' => 'Course draft, không được public.',
                'description' => 'Dữ liệu test không public.',
                'thumbnail_url' => 'https://example.com/images/cat-draft.jpg',
                'intro_video_url' => null,
                'price' => 100000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'draft',
                'is_featured' => false,
                'total_duration_seconds' => 1000,
                'published_at' => null,
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_HIDDEN Not Public',
                'slug' => 'cat-course-hidden-not-public',
                'short_description' => 'Course hidden, không được public.',
                'description' => 'Dữ liệu test hidden.',
                'thumbnail_url' => 'https://example.com/images/cat-hidden.jpg',
                'intro_video_url' => null,
                'price' => 100000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'hidden',
                'is_featured' => true,
                'total_duration_seconds' => 1000,
                'published_at' => $now->copy()->subDays(2),
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_PENDING_REVIEW Not Public',
                'slug' => 'cat-course-pending-review-not-public',
                'short_description' => 'Course pending_review, không được public.',
                'description' => 'Dữ liệu test pending review.',
                'thumbnail_url' => 'https://example.com/images/cat-pending.jpg',
                'intro_video_url' => null,
                'price' => 200000,
                'sale_price' => null,
                'level' => 'intermediate',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'pending_review',
                'is_featured' => false,
                'total_duration_seconds' => 1000,
                'published_at' => null,
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_REJECTED Not Public',
                'slug' => 'cat-course-rejected-not-public',
                'short_description' => 'Course rejected, không được public.',
                'description' => 'Dữ liệu test rejected.',
                'thumbnail_url' => 'https://example.com/images/cat-rejected.jpg',
                'intro_video_url' => null,
                'price' => 300000,
                'sale_price' => null,
                'level' => 'advanced',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'rejected',
                'is_featured' => false,
                'total_duration_seconds' => 1000,
                'published_at' => null,
                'admin_reject_reason' => 'Nội dung chưa đạt yêu cầu.',
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_APPROVED Not Public',
                'slug' => 'cat-course-approved-not-public',
                'short_description' => 'Course approved nhưng chưa published.',
                'description' => 'Dữ liệu test approved.',
                'thumbnail_url' => 'https://example.com/images/cat-approved.jpg',
                'intro_video_url' => null,
                'price' => 400000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'approved',
                'is_featured' => false,
                'total_duration_seconds' => 1000,
                'published_at' => null,
                'admin_reject_reason' => null,
                'deleted_at' => null,
            ],
            [
                'instructor_id' => $instructor01Id,
                'title' => 'COURSE_PUBLISHED Soft Deleted Not Public',
                'slug' => 'cat-course-published-soft-deleted-not-public',
                'short_description' => 'Course published nhưng soft deleted.',
                'description' => 'Dữ liệu test soft delete course.',
                'thumbnail_url' => 'https://example.com/images/cat-soft-deleted.jpg',
                'intro_video_url' => null,
                'price' => 500000,
                'sale_price' => null,
                'level' => 'beginner',
                'language' => 'vi',
                'requirements' => null,
                'outcomes' => null,
                'status' => 'published',
                'is_featured' => true,
                'total_duration_seconds' => 1000,
                'published_at' => $now->copy()->subDays(5),
                'admin_reject_reason' => null,
                'deleted_at' => $now,
            ],
        ];

        foreach ($courses as $course) {
            DB::table('courses')->updateOrInsert(
                ['slug' => $course['slug']],
                array_merge($course, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }
}
