<?php

namespace Tests\Feature\Final\Support;

final class FinalCaseCatalog
{
    public static function all(): array
    {
        return [
            'G1-001' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Migration fresh tạo đủ toàn bộ bảng FINAL mà không lỗi.'],
            'G1-002' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`users` tồn tại `password_hash` và không còn `password`.'],
            'G1-003' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Các bảng nghiệp vụ chính không còn `deleted_at`.'],
            'G1-004' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`courses` dùng `course_level`, không còn `level` legacy.'],
            'G1-005' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`courses` không còn `discount_percent`.'],
            'G1-006' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`revenues` không có cột `status` legacy.'],
            'G1-007' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`wishlist` dùng composite primary key `(user_id, course_id)`.'],
            'G1-008' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders` có `price_snapshot`.'],
            'G1-009' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders` có `discount_amount`.'],
            'G1-010' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders` có `commission_rule_id`.'],
            'G1-011' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders.order_code` bắt buộc và unique.'],
            'G1-012' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`revenues.order_id` unique: một order chỉ sinh tối đa một revenue.'],
            'G1-013' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`revenues` có `commission_rule_id` để truy vết rule đã áp dụng.'],
            'G1-014' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`sessions` có `refresh_token_hash`.'],
            'G1-015' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`user_otps` có `code_hash`, không lưu OTP dạng plain text.'],
            'G1-016' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`withdrawal_revenues` có composite key đúng.'],
            'G1-017' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`payout_accounts.user_id` là FK hợp lệ.'],
            'G1-018' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders.user_id` là FK hợp lệ.'],
            'G1-019' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders.course_id` là FK hợp lệ.'],
            'G1-020' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`orders.commission_rule_id` là FK hợp lệ.'],
            'G1-021' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Không cho insert order với `user_id` không tồn tại.'],
            'G1-022' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Không cho insert order với `course_id` không tồn tại.'],
            'G1-023' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Không cho insert revenue với `order_id` không tồn tại.'],
            'G1-024' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Không cho insert payout account với `user_id` không tồn tại.'],
            'G1-025' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Không cho insert enrollment với `order_id` không tồn tại.'],
            'G1-026' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Xóa user cascade đúng những bảng được phép cascade.'],
            'G1-027' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Xóa course cascade đúng pivot/quan hệ được phép.'],
            'G1-028' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Xóa category cascade đúng pivot `course_categories`.'],
            'G1-029' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Foreign key tài chính không được cascade làm mất lịch sử revenue/withdrawal ngoài thiết kế FINAL.'],
            'G1-030' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique email trên `users` hoạt động.'],
            'G1-031' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique phone trên `users` hoạt động khi phone khác NULL.'],
            'G1-032' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Nhiều user có phone NULL vẫn tạo được.'],
            'G1-033' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique slug trên `courses` hoạt động.'],
            'G1-034' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique slug trên `categories` hoạt động.'],
            'G1-035' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique `refresh_token_hash` trên sessions hoạt động.'],
            'G1-036' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Unique `provider_payout_id` trên withdrawal hoạt động nếu có giá trị.'],
            'G1-037' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/status của `courses` đúng tập giá trị FINAL.'],
            'G1-038' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/status của `orders` đúng tập giá trị FINAL.'],
            'G1-039' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/payment_status của `orders` đúng tập giá trị FINAL.'],
            'G1-040' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/status của `payout_accounts` đúng tập giá trị FINAL.'],
            'G1-041' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/status của `withdraw_requests` đúng tập giá trị FINAL.'],
            'G1-042' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/role của `users` đúng learner/instructor/admin.'],
            'G1-043' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'ENUM/status của `users` đúng active/inactive/suspended.'],
            'G1-044' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Giá trị enum ngoài FINAL bị DB từ chối.'],
            'G1-045' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Decimal tiền lưu chính xác số nguyên VND cần dùng.'],
            'G1-046' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`price_snapshot`, `discount_amount`, `amount` không bị trôi số.'],
            'G1-047' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Rate commission lưu đúng precision.'],
            'G1-048' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Timestamp nullable hoạt động đúng ở các trạng thái chưa xử lý.'],
            'G1-049' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Timestamp được ghi khi trạng thái chuyển đúng thời điểm.'],
            'G1-050' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'JSON fields như requirements/outcomes lưu và đọc được mảng rỗng.'],
            'G1-051' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Course cho phép `sale_price = NULL` khi không có campaign.'],
            'G1-052' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Order cho phép coupon_id NULL khi mua không giảm giá.'],
            'G1-053' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Order trial cho phép amount = 0 đúng trường hợp trial.'],
            'G1-054' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Order thường amount = 0 bị business layer chặn.'],
            'G1-055' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Migration có thể chạy lại từ database rỗng.'],
            'G1-056' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`migrate:fresh` trên `test11111` PASS.'],
            'G1-057' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`artisan about` boot app PASS.'],
            'G1-058' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`route:list` compile toàn bộ route PASS.'],
            'G1-059' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => '`git diff --check` không có whitespace error.'],
            'G1-060' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Model fillable/casts không nhắc field legacy đã bỏ.'],
            'G1-061' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Repository không query `deleted_at` ở schema FINAL.'],
            'G1-062' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Service không query `courses.discount_percent`.'],
            'G1-063' => ['group' => 'NHÓM 1', 'icon' => '🔴', 'label' => 'Auth code không query `users.password`.'],
            'G1-064' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Fixture test tự sinh dữ liệu unique, không phụ thuộc dữ liệu có sẵn.'],
            'G1-065' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Mỗi test rollback dữ liệu sau khi chạy.'],
            'G1-066' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Chạy cùng bộ test hai lần liên tiếp vẫn PASS.'],
            'G1-067' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Chạy riêng từng group không phụ thuộc group khác.'],
            'G1-068' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Tất cả foreign key/index/unique quan trọng vẫn tồn tại sau `migrate:fresh` và đúng tên/ý nghĩa FINAL.'],
            'G1-069' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Charset/collation của schema lưu và đọc đúng tiếng Việt có dấu.'],
            'G1-070' => ['group' => 'NHÓM 1', 'icon' => '🟢', 'label' => 'Các index/unique quan trọng dùng cho khóa ngoại, lookup order_code, email, slug và provider id tồn tại sau `migrate:fresh`.'],
            'G2-001' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Instructor tạo khóa học draft hợp lệ.'],
            'G2-002' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Learner không được tạo khóa học instructor.'],
            'G2-003' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Instructor không được sửa khóa học của instructor khác.'],
            'G2-004' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course draft lưu đúng title, slug, price, course_level.'],
            'G2-005' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Trùng slug khóa học bị từ chối.'],
            'G2-006' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course lưu giá lớn đúng precision.'],
            'G2-007' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`course_level=beginner` hợp lệ.'],
            'G2-008' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`course_level=intermediate` hợp lệ.'],
            'G2-009' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`course_level=advanced` hợp lệ.'],
            'G2-010' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`course_level=all_levels` hợp lệ.'],
            'G2-011' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => '`course_level` ngoài enum bị từ chối.'],
            'G2-012' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course trạng thái `draft` hợp lệ.'],
            'G2-013' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Chuyển draft → pending_review hợp lệ.'],
            'G2-014' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Admin duyệt pending_review → approved.'],
            'G2-015' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Approved → published khi đủ điều kiện xuất bản.'],
            'G2-016' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Admin reject pending_review → rejected và có lý do.'],
            'G2-017' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Instructor không tự chuyển course sang approved.'],
            'G2-018' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Instructor không tự publish course đang pending_review.'],
            'G2-019' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Published → hidden khi cần ẩn khóa học.'],
            'G2-020' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Hidden → published lại khi điều kiện cho phép.'],
            'G2-021' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Rejected không tự động thành published.'],
            'G2-022' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`published_at` chỉ có khi published.'],
            'G2-023' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`reviewed_by` ghi admin đã duyệt/reject.'],
            'G2-024' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => '`admin_reject_reason` chỉ có khi rejected.'],
            'G2-025' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Instructor sửa draft bình thường.'],
            'G2-026' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Instructor sửa rejected để gửi duyệt lại.'],
            'G2-027' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Instructor sửa các field quản trị trên course bị chặn.'],
            'G2-028' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Client không mass assign `reviewed_by`.'],
            'G2-029' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Client không mass assign `status=approved`.'],
            'G2-030' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Category root tạo thành công.'],
            'G2-031' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Category con cấp 2 tạo thành công.'],
            'G2-032' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Category cấp 3 bị từ chối; cấu trúc FINAL chỉ cho tối đa 2 cấp.'],
            'G2-033' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Category parent không tồn tại bị từ chối.'],
            'G2-034' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Category tự làm parent của chính nó bị từ chối.'],
            'G2-035' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Hai category trùng slug bị từ chối.'],
            'G2-036' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Category active hiển thị ở catalog.'],
            'G2-037' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Category inactive không được dùng như category public.'],
            'G2-038' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Một course gắn nhiều category.'],
            'G2-039' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Một category gắn nhiều course.'],
            'G2-040' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Cặp course-category trùng bị từ chối.'],
            'G2-041' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Xóa category gỡ pivot nhưng không xóa course.'],
            'G2-042' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Xóa course gỡ pivot nhưng không xóa category.'],
            'G2-043' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Instructor chỉ thấy course của chính mình trong dashboard.'],
            'G2-044' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Admin thấy được course của mọi instructor.'],
            'G2-045' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Learner không gọi API quản trị course.'],
            'G2-046' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Public chỉ thấy course published.'],
            'G2-047' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Public không thấy course draft.'],
            'G2-048' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Public không thấy course pending_review.'],
            'G2-049' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Public không thấy course rejected.'],
            'G2-050' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Public không thấy course hidden.'],
            'G2-051' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Thumbnail URL nullable.'],
            'G2-052' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Thumbnail public id nullable.'],
            'G2-053' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Intro video URL nullable.'],
            'G2-054' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Intro video id nullable.'],
            'G2-055' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course giữ Bunny/video fields hiện tại sau refactor pricing.'],
            'G2-056' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Không làm mất quan hệ section/lesson khi sửa metadata course.'],
            'G2-057' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Reorder category cập nhật sort_order đúng.'],
            'G2-058' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Reorder gửi ID category không tồn tại bị từ chối.'],
            'G2-059' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API index course filter theo status đúng.'],
            'G2-060' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API index course filter theo category đúng.'],
            'G2-061' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API index course filter theo level đúng.'],
            'G2-062' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API index course sort theo giá đúng.'],
            'G2-063' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API detail course trả đúng instructor.'],
            'G2-064' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'API detail course trả đúng category.'],
            'G2-065' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course không có coupon thì sale_price NULL hoặc bằng logic cache FINAL.'],
            'G2-066' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Course có active campaign thì sale_price phản ánh campaign đúng.'],
            'G2-067' => ['group' => 'NHÓM 2', 'icon' => '🔴', 'label' => 'Sửa giá course làm campaign hiện tại vi phạm rule phải bị từ chối hoặc đồng bộ đúng nghiệp vụ.'],
            'G2-068' => ['group' => 'NHÓM 2', 'icon' => '🟢', 'label' => 'Concurrent update course không làm mất trạng thái moderation.'],
            'G3-001' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Learner tạo pending order cho course chưa mua.'],
            'G3-002' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'User đã sở hữu course không tạo pending order mới.'],
            'G3-003' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Double click mua chỉ tạo một pending order hợp lệ.'],
            'G3-004' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order sinh `order_code` unique.'],
            'G3-005' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order chụp `price_snapshot` tại thời điểm tạo.'],
            'G3-006' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order chụp `discount_amount` tại thời điểm tạo.'],
            'G3-007' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order chụp `amount` cuối cùng tại thời điểm tạo.'],
            'G3-008' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order chụp `commission_rule_id` tại thời điểm tạo.'],
            'G3-009' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Course đổi giá sau đó không làm thay đổi order pending cũ.'],
            'G3-010' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Coupon inactive sau đó không làm thay đổi order pending cũ.'],
            'G3-011' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Coupon expired sau đó không làm thay đổi order pending cũ.'],
            'G3-012' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order mới sau khi coupon inactive không được giảm.'],
            'G3-013' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Order không coupon có discount_amount = 0.'],
            'G3-014' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Client không được gửi price_snapshot để ép giá.'],
            'G3-015' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Client không được gửi discount_amount để ép giảm.'],
            'G3-016' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Client không được gửi amount để ép giá.'],
            'G3-017' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Client không được ép `commission_rule_id`; backend tự snapshot rule áp dụng.'],
            'G3-018' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Pending order có payment_status=pending.'],
            'G3-019' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Thanh toán thành công chuyển order → paid.'],
            'G3-020' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Thanh toán thành công chuyển payment_status → paid.'],
            'G3-021' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'paid_at được ghi đúng khi payment thành công.'],
            'G3-022' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Payment method được ghi theo gateway thực tế.'],
            'G3-023' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'provider_transaction_id được lưu khi gateway trả về.'],
            'G3-024' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Thanh toán thiếu tiền không được mark paid.'],
            'G3-025' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Payment callback cho order không tồn tại bị từ chối.'],
            'G3-026' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Webhook thành công tạo side effects đúng một lần.'],
            'G3-027' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Webhook lặp cùng giao dịch không tạo duplicate enrollment.'],
            'G3-028' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Webhook lặp không tạo duplicate revenue.'],
            'G3-029' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Webhook lặp không tăng coupon usage hai lần.'],
            'G3-030' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Webhook token/signature sai bị từ chối.'],
            'G3-031' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Webhook amount không khớp bị từ chối.'],
            'G3-032' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Payment fail chuyển trạng thái failed đúng rule.'],
            'G3-033' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Payment fail lưu failed_reason.'],
            'G3-034' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Retry sau fail rồi success chuyển paid đúng một lần.'],
            'G3-035' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Cancel pending order chuyển cancelled.'],
            'G3-036' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Cancel order đã paid bị từ chối.'],
            'G3-037' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Expire pending order quá hạn theo command.'],
            'G3-038' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Pending chưa quá hạn không bị expire.'],
            'G3-039' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Paid order không bị expire.'],
            'G3-040' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Payment VNPay flow cũ vẫn hoạt động sau tích hợp coupon.'],
            'G3-041' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'SePay confirm thành công tìm đúng order.'],
            'G3-042' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'SePay confirm nội dung không khớp order bị từ chối.'],
            'G3-043' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'SePay xử lý đúng order_code trong nội dung chuyển khoản.'],
            'G3-044' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial tạo zero-paid order đúng đặc tả.'],
            'G3-045' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial dùng payment_method=coupon_trial.'],
            'G3-046' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial không gọi payment gateway.'],
            'G3-047' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial order ngay lập tức paid theo flow trial.'],
            'G3-048' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial không tạo revenue.'],
            'G3-049' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial tạo enrollment 7 ngày.'],
            'G3-050' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial→paid thật reuse enrollment cũ.'],
            'G3-051' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial→paid thật giữ nguyên progress.'],
            'G3-052' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Trial→paid thật xóa expires_at của enrollment.'],
            'G3-053' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Paid order thường tạo enrollment active.'],
            'G3-054' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Enrollment liên kết đúng user-course-order.'],
            'G3-055' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Enrollment trỏ order khác user bị từ chối ở business layer.'],
            'G3-056' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Enrollment trỏ order khác course bị từ chối.'],
            'G3-057' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Một order paid không tạo hai enrollment.'],
            'G3-058' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Wishlist item không đóng băng giá.'],
            'G3-059' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Khi bấm mua từ wishlist, order lấy giá hiện tại.'],
            'G3-060' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Giá phải trả tối thiểu 10.000 VND cho paid discount.'],
            'G3-061' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Discount làm amount 1–9.999 VND bị từ chối.'],
            'G3-062' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Amount đúng 10.000 VND được chấp nhận.'],
            'G3-063' => ['group' => 'NHÓM 3', 'icon' => '🔴', 'label' => 'Amount âm bị từ chối.'],
            'G3-064' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Transaction rollback toàn bộ khi payment side effect lỗi giữa chừng.'],
            'G3-065' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Concurrent payment cùng order chỉ một request thắng.'],
            'G3-066' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Concurrent webhook cùng transaction không duplicate side effect.'],
            'G3-067' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Lịch sử order vẫn đọc đúng snapshot sau khi course/coupon/rule thay đổi.'],
            'G3-068' => ['group' => 'NHÓM 3', 'icon' => '🟢', 'label' => 'Expire pending order chạy lặp nhiều lần vẫn idempotent và không đổi order đã ở trạng thái terminal.'],
            'G4-001' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Paid order hợp lệ tạo đúng một revenue.'],
            'G4-002' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Pending order không tạo revenue.'],
            'G4-003' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Failed order không tạo revenue.'],
            'G4-004' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Cancelled order không tạo revenue.'],
            'G4-005' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Trial zero order không tạo revenue.'],
            'G4-006' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue lưu đúng instructor_id.'],
            'G4-007' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue lưu đúng course_id.'],
            'G4-008' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue lưu đúng order_id.'],
            'G4-009' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue lưu đúng commission_rule_id.'],
            'G4-010' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue gross_amount bằng amount order paid.'],
            'G4-011' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'instructor_amount tính theo instructor_rate snapshot.'],
            'G4-012' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'platform_fee_amount tính theo platform_rate snapshot.'],
            'G4-013' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'instructor_amount + platform_fee_amount = gross_amount.'],
            'G4-014' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Rate 80/20 chia đúng số tiền.'],
            'G4-015' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Rate 70/30 chia đúng số tiền.'],
            'G4-016' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Rate 75/25 chia đúng số tiền.'],
            'G4-017' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Rate có decimal precision chia đúng.'],
            'G4-018' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Quy tắc làm tròn VND nhất quán.'],
            'G4-019' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Giá lẻ sau giảm vẫn chia tiền đúng helper rounding.'],
            'G4-020' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Thay commission rule sau khi order tạo không đổi revenue của order cũ.'],
            'G4-021' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Order cũ giữ commission_rule_id cũ.'],
            'G4-022' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Order mới dùng rule active mới.'],
            'G4-023' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Không được sửa rate của commission rule đã được order/revenue tham chiếu; phải tạo rule mới.'],
            'G4-024' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Tạo rule mới thay cho sửa rule cũ.'],
            'G4-025' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Không cho tồn tại đồng thời hai commission rule active của scope hiện tại.'],
            'G4-026' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Tắt rule cũ rồi bật rule mới thành công.'],
            'G4-027' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue không có `status` legacy; vòng đời dựa trên snapshot/thời gian/allocation theo schema FINAL.'],
            'G4-028' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'earned_at được ghi khi revenue phát sinh.'],
            'G4-029' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue vẫn tồn tại khi course đổi giá.'],
            'G4-030' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue vẫn tồn tại khi coupon bị inactive.'],
            'G4-031' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue vẫn tồn tại khi commission rule bị thay thế.'],
            'G4-032' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Không tạo duplicate revenue cho cùng order.'],
            'G4-033' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Retry side effect sau timeout không duplicate revenue.'],
            'G4-034' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Webhook lặp không duplicate revenue.'],
            'G4-035' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => '`syncMissingPaidOrderRevenues` chỉ backfill paid order có amount > 0.'],
            'G4-036' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => '`syncMissingPaidOrderRevenues` bỏ qua trial amount=0.'],
            'G4-037' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'RevenueShareService trả null đúng cho zero-amount order.'],
            'G4-038' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'RevenueShareService vẫn tạo revenue cho paid order thường.'],
            'G4-039' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Admin revenue list thấy đúng gross/instructor/platform.'],
            'G4-040' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Instructor chỉ thấy revenue của mình.'],
            'G4-041' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Instructor A không xem revenue của instructor B.'],
            'G4-042' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Filter revenue theo course đúng.'],
            'G4-043' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Filter revenue theo ngày đúng.'],
            'G4-044' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Tổng revenue dashboard bằng tổng dòng phù hợp.'],
            'G4-045' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Tổng platform fee bằng tổng platform_fee_amount.'],
            'G4-046' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Tổng instructor earning bằng tổng instructor_amount.'],
            'G4-047' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue có thể được phân bổ vào withdrawal.'],
            'G4-048' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Một revenue có thể bị phân bổ theo rule FINAL đúng giới hạn.'],
            'G4-049' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Tổng allocated_amount không vượt instructor_amount khả dụng.'],
            'G4-050' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue chưa rút được tính vào available balance theo rule.'],
            'G4-051' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue đã allocate đủ không còn available.'],
            'G4-052' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue allocate một phần còn phần dư available.'],
            'G4-053' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Concurrent withdrawal allocation không chiếm cùng balance hai lần.'],
            'G4-054' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Transaction rollback allocation khi withdrawal tạo lỗi.'],
            'G4-055' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Revenue với instructor khác withdrawal owner không được allocate.'],
            'G4-056' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Revenue âm hoặc zero không được coi là available payout.'],
            'G4-057' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue từ paid order cũ vẫn truy vết được order_code.'],
            'G4-058' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Admin order detail biết paid order có revenue.'],
            'G4-059' => ['group' => 'NHÓM 4', 'icon' => '🔴', 'label' => 'Paid order thiếu revenue được detect là inconsistency.'],
            'G4-060' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Trial paid zero không bị đánh inconsistency vì không cần revenue.'],
            'G4-061' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Số tiền commission không tính lại theo course price hiện tại.'],
            'G4-062' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Số tiền commission không tính lại theo rule hiện tại.'],
            'G4-063' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Snapshot bảo toàn lịch sử 70/30 khi admin đổi 80/20.'],
            'G4-064' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Report lịch sử hiển thị đúng rule đã áp dụng lúc bán.'],
            'G4-065' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Không dùng float sai lệch khi tính tiền.'],
            'G4-066' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Các amount cast/serialize API đúng định dạng.'],
            'G4-067' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Revenue FK bảo vệ dữ liệu orphan.'],
            'G4-068' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Xóa user/course theo rule FK không làm mất revenue lịch sử ngoài ý muốn.'],
            'G4-069' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Chạy batch sync nhiều lần vẫn idempotent.'],
            'G4-070' => ['group' => 'NHÓM 4', 'icon' => '🟢', 'label' => 'Concurrent finalize payment + sync revenue không duplicate row.'],
            'G5-001' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Instructor tạo payout account pending_verification.'],
            'G5-002' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin verify payout account thành verified.'],
            'G5-003' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Payout account chưa verified không được set default.'],
            'G5-004' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Verified account được set default.'],
            'G5-005' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Một user không có hai payout account default.'],
            'G5-006' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Disable payout account đang không default.'],
            'G5-007' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Disable payout account default xử lý default theo rule.'],
            'G5-008' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Learner không được tạo payout account instructor.'],
            'G5-009' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Instructor A không xem/sửa payout account của B.'],
            'G5-010' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Account number snapshot giữ nguyên trong withdrawal.'],
            'G5-011' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Account name snapshot giữ nguyên trong withdrawal.'],
            'G5-012' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Bank/provider snapshot giữ nguyên trong withdrawal.'],
            'G5-013' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Instructor gửi withdrawal khi đủ available balance.'],
            'G5-014' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Withdrawal vượt available balance bị từ chối.'],
            'G5-015' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Withdrawal amount <= 0 bị từ chối.'],
            'G5-016' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Khi tạo withdrawal, available_balance_before được snapshot.'],
            'G5-017' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Khi allocate, available_balance_after đúng.'],
            'G5-018' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Withdrawal status ban đầu pending.'],
            'G5-019' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin approve pending → approved.'],
            'G5-020' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Instructor tự approve withdrawal bị chặn.'],
            'G5-021' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Approve withdrawal của user khác bằng quyền instructor bị chặn.'],
            'G5-022' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Approved → processing khi bắt đầu payout.'],
            'G5-023' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Processing → paid khi chuyển tiền thành công.'],
            'G5-024' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'paid_at được ghi khi paid.'],
            'G5-025' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'processed_at được ghi theo flow.'],
            'G5-026' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'provider_payout_id lưu khi provider trả id.'],
            'G5-027' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'provider_payout_id duplicate bị từ chối.'],
            'G5-028' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Payout lỗi tự động chuyển failed hoặc manual_required đúng rule.'],
            'G5-029' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'failure_reason lưu khi provider lỗi.'],
            'G5-030' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin có thể mark_failed đúng state.'],
            'G5-031' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin có thể chuyển manual_required theo rule.'],
            'G5-032' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin manual mark-paid có audit fields cần thiết.'],
            'G5-033' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Không approve withdrawal đã paid.'],
            'G5-034' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Không reject withdrawal đã paid.'],
            'G5-035' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin reject pending withdrawal và lưu rejected_reason.'],
            'G5-036' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Balance được hoàn lại khi withdrawal reject/cancel đúng rule.'],
            'G5-037' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Balance không hoàn lại hai lần khi retry callback.'],
            'G5-038' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Withdrawal allocation liên kết đúng revenue.'],
            'G5-039' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Một withdrawal có nhiều revenue allocation.'],
            'G5-040' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Tổng allocation vượt withdrawal amount bị từ chối.'],
            'G5-041' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Tổng allocation vượt revenue available bị từ chối.'],
            'G5-042' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Concurrent hai withdrawal không tiêu cùng balance.'],
            'G5-043' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'lockForUpdate/transaction bảo vệ race condition balance.'],
            'G5-044' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Retry provider idempotent không tạo hai payout.'],
            'G5-045' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Timeout provider nhưng response retry xử lý đúng.'],
            'G5-046' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Manual payout không phá idempotency provider.'],
            'G5-047' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin list filter pending đúng.'],
            'G5-048' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin list filter processing đúng.'],
            'G5-049' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin list filter manual_required đúng.'],
            'G5-050' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin list filter paid đúng.'],
            'G5-051' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin list filter failed đúng.'],
            'G5-052' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Instructor list chỉ thấy withdrawal của mình.'],
            'G5-053' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Detail withdrawal trả đúng payout snapshot.'],
            'G5-054' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'Không trả số tài khoản nhạy cảm quá mức cho role không phù hợp.'],
            'G5-055' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'OTP đổi payout account được yêu cầu đúng flow.'],
            'G5-056' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'OTP sai không đổi payout account.'],
            'G5-057' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'OTP hết hạn không đổi payout account.'],
            'G5-058' => ['group' => 'NHÓM 5', 'icon' => '🔴', 'label' => 'OTP đã dùng không được dùng lại.'],
            'G5-059' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Payout account change sau OTP không làm thay đổi snapshot withdrawal cũ.'],
            'G5-060' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Admin chuyển thủ công không sửa revenue snapshot.'],
            'G5-061' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Paid withdrawal vẫn truy vết được revenue allocations.'],
            'G5-062' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Xóa/disable payout account không xóa lịch sử withdrawal.'],
            'G5-063' => ['group' => 'NHÓM 5', 'icon' => '🟢', 'label' => 'Transaction rollback toàn bộ khi allocation lỗi giữa chừng.'],
            'G6-001' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Learner đăng ký bằng email hợp lệ.'],
            'G6-002' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Instructor đăng ký bằng flow instructor hợp lệ.'],
            'G6-003' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Đăng ký email trùng bị từ chối.'],
            'G6-004' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Đăng ký phone trùng bị từ chối nếu phone có giá trị.'],
            'G6-005' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Nhiều tài khoản phone NULL vẫn hợp lệ.'],
            'G6-006' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Password quá yếu bị validation từ chối.'],
            'G6-007' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Email sai định dạng bị từ chối.'],
            'G6-008' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Role từ client cố ép thành admin bị chặn.'],
            'G6-009' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Client không mass assign `locked`, `status`, `email_verified_at`.'],
            'G6-010' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Password được lưu vào `password_hash`.'],
            'G6-011' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Không lưu plain password vào DB.'],
            'G6-012' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Login đúng email/password thành công.'],
            'G6-013' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Login sai password bị từ chối.'],
            'G6-014' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Login email không tồn tại bị từ chối.'],
            'G6-015' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'User inactive không login.'],
            'G6-016' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'User suspended không login.'],
            'G6-017' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'User locked không login.'],
            'G6-018' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'last_login_at cập nhật khi login thành công.'],
            'G6-019' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Login tạo session/refresh token hợp lệ.'],
            'G6-020' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Refresh token được lưu dạng hash.'],
            'G6-021' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Refresh token raw không xuất hiện trong DB.'],
            'G6-022' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Refresh token giả bị từ chối.'],
            'G6-023' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Refresh token hết hạn bị từ chối.'],
            'G6-024' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Refresh token revoked bị từ chối.'],
            'G6-025' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Logout revoke session hiện tại.'],
            'G6-026' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Token sau logout không dùng lại được.'],
            'G6-027' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Session ghi device_name.'],
            'G6-028' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Session ghi ip_address.'],
            'G6-029' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Session ghi user_agent.'],
            'G6-030' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'User A không dùng token của user B để truy cập tài nguyên riêng.'],
            'G6-031' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Learner không vào route instructor.'],
            'G6-032' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Instructor không vào route admin.'],
            'G6-033' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Admin vào route admin hợp lệ.'],
            'G6-034' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Request không token vào route auth required trả 401.'],
            'G6-035' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Token malformed trả 401.'],
            'G6-036' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Token hết hạn trả 401.'],
            'G6-037' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => '`/auth/me` trả đúng user hiện tại.'],
            'G6-038' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => '`/auth/me` không leak password_hash.'],
            'G6-039' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Forgot password tạo OTP đúng purpose.'],
            'G6-040' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'OTP được lưu dưới `code_hash`.'],
            'G6-041' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP plain code không được lưu DB.'],
            'G6-042' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Verify OTP đúng code + đúng purpose thành công.'],
            'G6-043' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP đúng code nhưng sai purpose bị từ chối.'],
            'G6-044' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP sai code bị từ chối.'],
            'G6-045' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP hết hạn bị từ chối.'],
            'G6-046' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP đã used bị từ chối.'],
            'G6-047' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP của user A không dùng cho user B.'],
            'G6-048' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'attempts tăng khi nhập OTP sai.'],
            'G6-049' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Quá số attempts bị khóa OTP.'],
            'G6-050' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Resend OTP làm OTP cũ mất hiệu lực theo rule.'],
            'G6-051' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Reset password sau OTP hợp lệ đổi password_hash.'],
            'G6-052' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Reset password không OTP bị từ chối.'],
            'G6-053' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Reset password với OTP đã dùng bị từ chối.'],
            'G6-054' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Đổi payout account yêu cầu purpose OTP riêng.'],
            'G6-055' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP password_reset không dùng để đổi payout account.'],
            'G6-056' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Email verification link đúng hash thành công.'],
            'G6-057' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Email verification hash sai bị từ chối.'],
            'G6-058' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Resend verify email chỉ áp dụng user chưa verify.'],
            'G6-059' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'User đã verify không spam resend theo rule.'],
            'G6-060' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'IDOR profile: user A không sửa profile B.'],
            'G6-061' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'IDOR payout: user A không sửa payout B.'],
            'G6-062' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'Mass assignment không đổi role thành admin.'],
            'G6-063' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'SQL injection payload trong email/search không phá query.'],
            'G6-064' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'XSS payload trong profile text được xử lý an toàn ở tầng output/validation phù hợp.'],
            'G6-065' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'Xóa user cascade session và OTP đúng schema, không để token sống sót.'],
            'G6-066' => ['group' => 'NHÓM 6', 'icon' => '🔴', 'label' => 'OTP resend liên tục không được tạo vô hạn OTP còn hiệu lực đồng thời cho cùng user + purpose.'],
            'G6-067' => ['group' => 'NHÓM 6', 'icon' => '🟢', 'label' => 'OTP mới thay thế/khóa hiệu lực OTP cũ theo đúng cơ chế hiện tại.'],
            'G8-001' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Instructor tạo discount campaign cho course của mình.'],
            'G8-002' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Instructor không tạo campaign cho course người khác.'],
            'G8-003' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Learner không gọi API instructor coupon.'],
            'G8-004' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Chưa đăng nhập không gọi API instructor coupon.'],
            'G8-005' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Client không tự truyền instructor_id để chiếm ownership.'],
            'G8-006' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Client không tự truyền user_id để chiếm ownership.'],
            'G8-007' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Client không tự chọn coupon code.'],
            'G8-008' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Backend sinh coupon code unique.'],
            'G8-009' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Percent discount hợp lệ trong giới hạn.'],
            'G8-010' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Percent discount <= 0 bị từ chối.'],
            'G8-011' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Fixed discount hợp lệ.'],
            'G8-012' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Percent coupon dùng `max_discount_amount` hợp lệ.'],
            'G8-013' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Fixed campaign để `max_discount_amount=NULL`.'],
            'G8-014' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Fixed campaign gửi max_discount_amount trái rule bị từ chối.'],
            'G8-015' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Discount không làm giá phải trả dưới 10.000 VND.'],
            'G8-016' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Giá sau giảm 9.999 VND bị từ chối.'],
            'G8-017' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Giá sau giảm đúng 10.000 VND hợp lệ.'],
            'G8-018' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Đúng start_at tự có hiệu lực không cần scheduler.'],
            'G8-019' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Active campaign áp giá đúng.'],
            'G8-020' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Qua end_at tự hết hiệu lực.'],
            'G8-021' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Disable active → inactive.'],
            'G8-022' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Delete coupon chỉ inactive, không hard delete.'],
            'G8-023' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'History campaign vẫn tồn tại sau inactive.'],
            'G8-024' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Campaign terminal `expired/used_up` không được kích hoạt lại.'],
            'G8-025' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Course không campaign tạo campaign mới được.'],
            'G8-026' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Active campaign overlap bị reject.'],
            'G8-027' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Scheduled campaign overlap bị reject.'],
            'G8-028' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Active + future overlap bị reject.'],
            'G8-029' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Expired campaign cho phép tạo campaign mới.'],
            'G8-030' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Inactive campaign cho phép tạo campaign mới.'],
            'G8-031' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Một course có nhiều campaign lịch sử.'],
            'G8-032' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Hai request concurrent overlap không tạo hai campaign hợp lệ.'],
            'G8-033' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Discount `usage_limit=NULL` nghĩa unlimited.'],
            'G8-034' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Discount usage_limit lớn như 1000 hợp lệ.'],
            'G8-035' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'usage_limit < used_count bị từ chối.'],
            'G8-036' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Tạo pending order chưa tăng used_count.'],
            'G8-037' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Payment success tăng used_count đúng một lần.'],
            'G8-038' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Payment fail không tăng used_count.'],
            'G8-039' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Cancel order không tăng used_count.'],
            'G8-040' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Webhook lặp không tăng used_count hai lần.'],
            'G8-041' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Lượt dùng cuối chuyển campaign → used_up.'],
            'G8-042' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'used_up reset/sync sale_price đúng.'],
            'G8-043' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Hai payment tranh lượt cuối không vượt usage_limit.'],
            'G8-044' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Double disable không corrupt state.'],
            'G8-045' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Retry fail→success chỉ side effect một lần.'],
            'G8-046' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Order snapshot đúng giá gốc/discount/amount/coupon.'],
            'G8-047' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'OrderService không tin `sale_price` cache stale.'],
            'G8-048' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Pending order giữ snapshot sau coupon inactive.'],
            'G8-049' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Pending order giữ snapshot sau campaign expired.'],
            'G8-050' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Double click mua không tạo hai pending order.'],
            'G8-051' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'User A giữ snapshot; user B không được giảm sau used_up.'],
            'G8-052' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Đổi course price khi campaign active tính lại sale_price.'],
            'G8-053' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Pending order cũ không đổi sau course đổi giá.'],
            'G8-054' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Client không ép sale_price/discount_amount/amount.'],
            'G8-055' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial campaign có các discount field nullable đúng schema.'],
            'G8-056' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial duration chỉ 1–3 ngày.'],
            'G8-057' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Trial duration ngoài 1–3 bị từ chối.'],
            'G8-058' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial tạo paid zero order + enrollment 7 ngày + tăng used_count.'],
            'G8-059' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial không cần gateway/webhook.'],
            'G8-060' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial không tạo revenue.'],
            'G8-061' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Learner chỉ trial một lần mỗi course.'],
            'G8-062' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Instructor không tạo trial thứ ba trong cùng tháng.'],
            'G8-063' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Trial→paid thật reuse enrollment và giữ progress.'],
            'G8-064' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Sửa cùng một trial campaign nhiều lần không bị tính thành nhiều campaign trong quota tháng.'],
            'G8-065' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Instructor ở danh sách quản lý hiện tại không thấy campaign đã `inactive/expired/used_up` nếu API current-list chỉ trả campaign còn quản lý được.'],
            'G8-066' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Admin có thể truy vấn lịch sử campaign đầy đủ theo các trạng thái FINAL mà không làm mất record lịch sử.'],
            'G8-067' => ['group' => 'NHÓM 8', 'icon' => '🔴', 'label' => 'Instructor A không xem detail/history campaign thuộc instructor B.'],
            'G8-068' => ['group' => 'NHÓM 8', 'icon' => '🟢', 'label' => 'Khi campaign thay đổi trạng thái làm mất hiệu lực, `sale_price` cache được đồng bộ lại đúng giá hiện hành.'],
        ];
    }
}